tftp-client.exe localhost:69 cmds/BOOT.bin BOOT.bin
tftp-client.exe localhost:69 cmds/ip.txt ip.txt
tftp-client.exe localhost:69 cmds/stop.txt stop.txt
tftp-client.exe localhost:69 cmds/reboot.txt reboot.txt
tftp-client.exe localhost:69 cmds/brand.txt brand.txt
tftp-client.exe localhost:69 cmds/filnames.txt filnames.txt
tftp-client.exe localhost:69 cmds/artnmod.txt artnmod.txt
tftp-client.exe localhost:69 cmds/rgbwmode.txt rgbwmode.txt
tftp-client.exe localhost:69 cmds/crop.txt crop.txt
tftp-client.exe localhost:69 cmds/mac.txt mac.txt
tftp-client.exe localhost:69 cmds/dummy.txt dummy.txt
tftp-client.exe localhost:69 cmds/error.txt error.txt